steps:
# Install dependencies and run tests
- name: 'node:18'
  entrypoint: npm
  args: ['ci']

- name: 'node:18'
  entrypoint: npm
  args: ['test']
  
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/budget-frontend', '.']

# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/budget-frontend']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'budget-frontend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/budget-frontend'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8080'
  
images:
- 'gcr.io/$PROJECT_ID/budget-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
